# Generated by Django 4.1.2 on 2022-12-09 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uweflixApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStatement',
            fields=[
                ('statementID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('clubID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uweflixApp.club')),
            ],
        ),
    ]
