# Generated by Django 4.1.3 on 2023-01-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uweflixApp', '0002_monthlystatement'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
